-- 그룹 함수

SELECT MAX(STU_HEIGHT) AS MAX_HEIGHT -- MIN
FROM STUDENT;

SELECT AVG(STU_HEIGHT) "평균 키"
FROM STUDENT;

SELECT SUM(STU_HEIGHT)
FROM STUDENT;

SELECT STU_NAME 이름 FROM STUDENT;
SELECT STU_NAME AS 이름 -- AS는 생략이 가능
FROM STUDENT;

SELECT * FROM ENROL;