SELECT *
FROM PROFESSOR
WHERE LENGTH(ID) >= 6;

UPDATE PROFESSOR
SET 
    PAY = PAY + 50
WHERE LENGTH(ID) >= 6;

ROLLBACK;

DELETE FROM PROFESSOR;

SELECT * FROM STUDENT;
    
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES('12341234', '홍길동', '기계');

INSERT INTO STUDNET
VALUES('12345678', '김철수', '전기전자', 1, 'A', 'M', 175, NULL);
//


