-- 4. DELETE (레코드 삭제)
SELECT * FROM STUDENT;
DELETE FROM STUDENT;

DELETE FROM STUDENT WHERE STU_NAME = '홍길동';
DELETE FROM STUDENT WHERE STU_NAME = '홍길동';

DELETE FROM STUDENT WHERE STU_NAME IN ('김철수', '홍길동');
COMMIT;
ROLLBACK;