SELECT *
FROM PROFESSOR
WHERE BONUS IS NOT NULL; -- IS NOT NULL
-- IN, LIKE, BETWEEN, IS NULL(IS NOT NULL)

-- 서브쿼리( 쿼리안에 또다른 쿼리)
SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT
);

-- 학생들의 전체 평균 키보다 큰 키를 가진 학생 출력
SELECT *
FROM STUDENT
WHERE STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
);